# Generated by Django 4.1.7 on 2023-06-07 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superset', '0017_alter_company_universities_company_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_universities',
            old_name='universities',
            new_name='college',
        ),
        migrations.AlterField(
            model_name='student',
            name='Photo',
            field=models.ImageField(blank=True, upload_to='profile_photo/'),
        ),
    ]
